# Generated by Django 5.0.6 on 2024-05-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='publications',
        ),
    ]
