# Generated by Django 5.0.6 on 2024-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_appuser_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='publications_count',
            field=models.IntegerField(default=0, verbose_name='Publications'),
        ),
    ]
